// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleIAMV1

/// BigQuery request and response messages for audit log.
/// Note: `Table.schema` has been deprecated in favor of `Table.schemaJson`.
/// `Table.schema` may continue to be present in your logs during this
/// transition.
public struct AuditData: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// A job completion event.
  public var jobCompletedEvent: JobCompletedEvent? = nil

  /// Information about the table access events.
  public var tableDataReadEvents: [TableDataReadEvent] = []

  /// Request data for each BigQuery method.
  public var request: OneOf_Request? = nil

  /// Response data for each BigQuery method.
  public var response: OneOf_Response? = nil

  /// Initialize a new instance of `AuditData`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AuditData().with { $0.tableInsertRequest = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case tableInsertRequest = "tableInsertRequest"
    case tableUpdateRequest = "tableUpdateRequest"
    case datasetListRequest = "datasetListRequest"
    case datasetInsertRequest = "datasetInsertRequest"
    case datasetUpdateRequest = "datasetUpdateRequest"
    case jobInsertRequest = "jobInsertRequest"
    case jobQueryRequest = "jobQueryRequest"
    case jobGetQueryResultsRequest = "jobGetQueryResultsRequest"
    case tableDataListRequest = "tableDataListRequest"
    case setIamPolicyRequest = "setIamPolicyRequest"
    case tableInsertResponse = "tableInsertResponse"
    case tableUpdateResponse = "tableUpdateResponse"
    case datasetInsertResponse = "datasetInsertResponse"
    case datasetUpdateResponse = "datasetUpdateResponse"
    case jobInsertResponse = "jobInsertResponse"
    case jobQueryResponse = "jobQueryResponse"
    case jobGetQueryResultsResponse = "jobGetQueryResultsResponse"
    case jobQueryDoneResponse = "jobQueryDoneResponse"
    case policyResponse = "policyResponse"
    case jobCompletedEvent = "jobCompletedEvent"
    case tableDataReadEvents = "tableDataReadEvents"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.jobCompletedEvent = try container.decodeIfPresent(
      JobCompletedEvent.self, forKey: .jobCompletedEvent)
    self.tableDataReadEvents = try container.decode(
      [TableDataReadEvent].self, forKey: .tableDataReadEvents)

    var request: OneOf_Request? = nil
    let requestCheckAndSet = {
      if request != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'request'"))
      }
      request = $0
    }
    if let tableInsertRequest = try container.decodeIfPresent(
      TableInsertRequest?.self, forKey: .tableInsertRequest)
    {
      try requestCheckAndSet(.tableInsertRequest(tableInsertRequest))
    }
    if let tableUpdateRequest = try container.decodeIfPresent(
      TableUpdateRequest?.self, forKey: .tableUpdateRequest)
    {
      try requestCheckAndSet(.tableUpdateRequest(tableUpdateRequest))
    }
    if let datasetListRequest = try container.decodeIfPresent(
      DatasetListRequest?.self, forKey: .datasetListRequest)
    {
      try requestCheckAndSet(.datasetListRequest(datasetListRequest))
    }
    if let datasetInsertRequest = try container.decodeIfPresent(
      DatasetInsertRequest?.self, forKey: .datasetInsertRequest)
    {
      try requestCheckAndSet(.datasetInsertRequest(datasetInsertRequest))
    }
    if let datasetUpdateRequest = try container.decodeIfPresent(
      DatasetUpdateRequest?.self, forKey: .datasetUpdateRequest)
    {
      try requestCheckAndSet(.datasetUpdateRequest(datasetUpdateRequest))
    }
    if let jobInsertRequest = try container.decodeIfPresent(
      JobInsertRequest?.self, forKey: .jobInsertRequest)
    {
      try requestCheckAndSet(.jobInsertRequest(jobInsertRequest))
    }
    if let jobQueryRequest = try container.decodeIfPresent(
      JobQueryRequest?.self, forKey: .jobQueryRequest)
    {
      try requestCheckAndSet(.jobQueryRequest(jobQueryRequest))
    }
    if let jobGetQueryResultsRequest = try container.decodeIfPresent(
      JobGetQueryResultsRequest?.self, forKey: .jobGetQueryResultsRequest)
    {
      try requestCheckAndSet(.jobGetQueryResultsRequest(jobGetQueryResultsRequest))
    }
    if let tableDataListRequest = try container.decodeIfPresent(
      TableDataListRequest?.self, forKey: .tableDataListRequest)
    {
      try requestCheckAndSet(.tableDataListRequest(tableDataListRequest))
    }
    if let setIamPolicyRequest = try container.decodeIfPresent(
      GoogleIAMV1.SetIamPolicyRequest?.self, forKey: .setIamPolicyRequest)
    {
      try requestCheckAndSet(.setIamPolicyRequest(setIamPolicyRequest))
    }
    self.request = request

    var response: OneOf_Response? = nil
    let responseCheckAndSet = {
      if response != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'response'"))
      }
      response = $0
    }
    if let tableInsertResponse = try container.decodeIfPresent(
      TableInsertResponse?.self, forKey: .tableInsertResponse)
    {
      try responseCheckAndSet(.tableInsertResponse(tableInsertResponse))
    }
    if let tableUpdateResponse = try container.decodeIfPresent(
      TableUpdateResponse?.self, forKey: .tableUpdateResponse)
    {
      try responseCheckAndSet(.tableUpdateResponse(tableUpdateResponse))
    }
    if let datasetInsertResponse = try container.decodeIfPresent(
      DatasetInsertResponse?.self, forKey: .datasetInsertResponse)
    {
      try responseCheckAndSet(.datasetInsertResponse(datasetInsertResponse))
    }
    if let datasetUpdateResponse = try container.decodeIfPresent(
      DatasetUpdateResponse?.self, forKey: .datasetUpdateResponse)
    {
      try responseCheckAndSet(.datasetUpdateResponse(datasetUpdateResponse))
    }
    if let jobInsertResponse = try container.decodeIfPresent(
      JobInsertResponse?.self, forKey: .jobInsertResponse)
    {
      try responseCheckAndSet(.jobInsertResponse(jobInsertResponse))
    }
    if let jobQueryResponse = try container.decodeIfPresent(
      JobQueryResponse?.self, forKey: .jobQueryResponse)
    {
      try responseCheckAndSet(.jobQueryResponse(jobQueryResponse))
    }
    if let jobGetQueryResultsResponse = try container.decodeIfPresent(
      JobGetQueryResultsResponse?.self, forKey: .jobGetQueryResultsResponse)
    {
      try responseCheckAndSet(.jobGetQueryResultsResponse(jobGetQueryResultsResponse))
    }
    if let jobQueryDoneResponse = try container.decodeIfPresent(
      JobQueryDoneResponse?.self, forKey: .jobQueryDoneResponse)
    {
      try responseCheckAndSet(.jobQueryDoneResponse(jobQueryDoneResponse))
    }
    if let policyResponse = try container.decodeIfPresent(
      GoogleIAMV1.Policy?.self, forKey: .policyResponse)
    {
      try responseCheckAndSet(.policyResponse(policyResponse))
    }
    self.response = response
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.jobCompletedEvent, forKey: .jobCompletedEvent)
    try container.encode(self.tableDataReadEvents, forKey: .tableDataReadEvents)

    if let choice = self.request {
      switch choice {
      case .tableInsertRequest(let value):
        try container.encode(value, forKey: .tableInsertRequest)
      case .tableUpdateRequest(let value):
        try container.encode(value, forKey: .tableUpdateRequest)
      case .datasetListRequest(let value):
        try container.encode(value, forKey: .datasetListRequest)
      case .datasetInsertRequest(let value):
        try container.encode(value, forKey: .datasetInsertRequest)
      case .datasetUpdateRequest(let value):
        try container.encode(value, forKey: .datasetUpdateRequest)
      case .jobInsertRequest(let value):
        try container.encode(value, forKey: .jobInsertRequest)
      case .jobQueryRequest(let value):
        try container.encode(value, forKey: .jobQueryRequest)
      case .jobGetQueryResultsRequest(let value):
        try container.encode(value, forKey: .jobGetQueryResultsRequest)
      case .tableDataListRequest(let value):
        try container.encode(value, forKey: .tableDataListRequest)
      case .setIamPolicyRequest(let value):
        try container.encode(value, forKey: .setIamPolicyRequest)
      }
    }

    if let choice = self.response {
      switch choice {
      case .tableInsertResponse(let value):
        try container.encode(value, forKey: .tableInsertResponse)
      case .tableUpdateResponse(let value):
        try container.encode(value, forKey: .tableUpdateResponse)
      case .datasetInsertResponse(let value):
        try container.encode(value, forKey: .datasetInsertResponse)
      case .datasetUpdateResponse(let value):
        try container.encode(value, forKey: .datasetUpdateResponse)
      case .jobInsertResponse(let value):
        try container.encode(value, forKey: .jobInsertResponse)
      case .jobQueryResponse(let value):
        try container.encode(value, forKey: .jobQueryResponse)
      case .jobGetQueryResultsResponse(let value):
        try container.encode(value, forKey: .jobGetQueryResultsResponse)
      case .jobQueryDoneResponse(let value):
        try container.encode(value, forKey: .jobQueryDoneResponse)
      case .policyResponse(let value):
        try container.encode(value, forKey: .policyResponse)
      }
    }
  }

  /// Request data for each BigQuery method.
  public enum OneOf_Request: Codable, Equatable, Sendable {
    /// Table insert request.
    indirect case tableInsertRequest(TableInsertRequest?)
    /// Table update request.
    indirect case tableUpdateRequest(TableUpdateRequest?)
    /// Dataset list request.
    indirect case datasetListRequest(DatasetListRequest?)
    /// Dataset insert request.
    indirect case datasetInsertRequest(DatasetInsertRequest?)
    /// Dataset update request.
    indirect case datasetUpdateRequest(DatasetUpdateRequest?)
    /// Job insert request.
    indirect case jobInsertRequest(JobInsertRequest?)
    /// Job query request.
    indirect case jobQueryRequest(JobQueryRequest?)
    /// Job get query results request.
    indirect case jobGetQueryResultsRequest(JobGetQueryResultsRequest?)
    /// Table data-list request.
    indirect case tableDataListRequest(TableDataListRequest?)
    /// Iam policy request.
    indirect case setIamPolicyRequest(GoogleIAMV1.SetIamPolicyRequest?)
  }

  /// Response data for each BigQuery method.
  public enum OneOf_Response: Codable, Equatable, Sendable {
    /// Table insert response.
    indirect case tableInsertResponse(TableInsertResponse?)
    /// Table update response.
    indirect case tableUpdateResponse(TableUpdateResponse?)
    /// Dataset insert response.
    indirect case datasetInsertResponse(DatasetInsertResponse?)
    /// Dataset update response.
    indirect case datasetUpdateResponse(DatasetUpdateResponse?)
    /// Job insert response.
    indirect case jobInsertResponse(JobInsertResponse?)
    /// Job query response.
    indirect case jobQueryResponse(JobQueryResponse?)
    /// Job get query results response.
    indirect case jobGetQueryResultsResponse(JobGetQueryResultsResponse?)
    /// Deprecated: Job query-done response. Use this information for usage
    /// analysis.
    indirect case jobQueryDoneResponse(JobQueryDoneResponse?)
    /// Iam Policy.
    indirect case policyResponse(GoogleIAMV1.Policy?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.logging.v1.AuditData"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
