// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// An access control list.
public struct BigQueryAcl: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Access control entry list.
  public var entries: [BigQueryAcl.Entry] = []

  /// Initialize a new instance of `BigQueryAcl`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BigQueryAcl().with { $0.entries = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Access control entry.
  public struct Entry: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The granted role, which can be `READER`, `WRITER`, or `OWNER`.
    public var role: Swift.String = Swift.String()

    /// Grants access to a group identified by an email address.
    public var groupEmail: Swift.String = Swift.String()

    /// Grants access to a user identified by an email address.
    public var userEmail: Swift.String = Swift.String()

    /// Grants access to all members of a domain.
    public var domain: Swift.String = Swift.String()

    /// Grants access to special groups. Valid groups are `PROJECT_OWNERS`,
    /// `PROJECT_READERS`, `PROJECT_WRITERS` and `ALL_AUTHENTICATED_USERS`.
    public var specialGroup: Swift.String = Swift.String()

    /// Grants access to a BigQuery View.
    public var viewName: TableName? = nil

    /// Initialize a new instance of `Entry`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Entry().with { $0.role = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.bigquery.logging.v1.BigQueryAcl.Entry"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.logging.v1.BigQueryAcl"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
