// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An access control list.
public struct BigQueryAcl: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Access control entry list.
  public var entries: [BigQueryAcl.Entry] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BigQueryAcl`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BigQueryAcl().with { $0.entries = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let entries = CodingKeys(stringValue: "entries")

    static let _knownKeys: Set<Swift.String> = [
      "entries"
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([BigQueryAcl.Entry].self, forKey: .entries) {
      self.entries = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.entries, forKey: .entries)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Access control entry.
  public struct Entry: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The granted role, which can be `READER`, `WRITER`, or `OWNER`.
    public var role: Swift.String = Swift.String()

    /// Grants access to a group identified by an email address.
    public var groupEmail: Swift.String = Swift.String()

    /// Grants access to a user identified by an email address.
    public var userEmail: Swift.String = Swift.String()

    /// Grants access to all members of a domain.
    public var domain: Swift.String = Swift.String()

    /// Grants access to special groups. Valid groups are `PROJECT_OWNERS`,
    /// `PROJECT_READERS`, `PROJECT_WRITERS` and `ALL_AUTHENTICATED_USERS`.
    public var specialGroup: Swift.String = Swift.String()

    /// Grants access to a BigQuery View.
    public var viewName: TableName? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Entry`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Entry().with { $0.role = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let role = CodingKeys(stringValue: "role")
      static let groupEmail = CodingKeys(stringValue: "groupEmail")
      static let userEmail = CodingKeys(stringValue: "userEmail")
      static let domain = CodingKeys(stringValue: "domain")
      static let specialGroup = CodingKeys(stringValue: "specialGroup")
      static let viewName = CodingKeys(stringValue: "viewName")

      static let _knownKeys: Set<Swift.String> = [
        "role",
        "groupEmail",
        "userEmail",
        "domain",
        "specialGroup",
        "viewName",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .role) {
        self.role = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .groupEmail) {
        self.groupEmail = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .userEmail) {
        self.userEmail = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .domain) {
        self.domain = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .specialGroup) {
        self.specialGroup = value
      }
      self.viewName = try container.decodeIfPresent(TableName.self, forKey: .viewName)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.role, forKey: .role)
      try container.encode(self.groupEmail, forKey: .groupEmail)
      try container.encode(self.userEmail, forKey: .userEmail)
      try container.encode(self.domain, forKey: .domain)
      try container.encode(self.specialGroup, forKey: .specialGroup)
      try container.encodeIfPresent(self.viewName, forKey: .viewName)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `Entry`: `"type.googleapis.com/google.cloud.bigquery.logging.v1.BigQueryAcl.Entry"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.bigquery.logging.v1.BigQueryAcl.Entry"
    }

    /// Initialize an instance of `Entry` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.bigquery.logging.v1.BigQueryAcl.Entry"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `Entry` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The type URL for `BigQueryAcl`: `"type.googleapis.com/google.cloud.bigquery.logging.v1.BigQueryAcl"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.logging.v1.BigQueryAcl"
  }

  /// Initialize an instance of `BigQueryAcl` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.bigquery.logging.v1.BigQueryAcl"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `BigQueryAcl` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
