// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Describes a job.
public struct Job: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Job name.
  public var jobName: JobName? = nil

  /// Job configuration.
  public var jobConfiguration: JobConfiguration? = nil

  /// Job status.
  public var jobStatus: JobStatus? = nil

  /// Job statistics.
  public var jobStatistics: JobStatistics? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Job`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Job().with { $0.jobName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let jobName = CodingKeys(stringValue: "jobName")
    static let jobConfiguration = CodingKeys(stringValue: "jobConfiguration")
    static let jobStatus = CodingKeys(stringValue: "jobStatus")
    static let jobStatistics = CodingKeys(stringValue: "jobStatistics")

    static let _knownKeys: Set<Swift.String> = [
      "jobName",
      "jobConfiguration",
      "jobStatus",
      "jobStatistics",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.jobName = try container.decodeIfPresent(JobName.self, forKey: .jobName)
    self.jobConfiguration = try container.decodeIfPresent(
      JobConfiguration.self, forKey: .jobConfiguration)
    self.jobStatus = try container.decodeIfPresent(JobStatus.self, forKey: .jobStatus)
    self.jobStatistics = try container.decodeIfPresent(JobStatistics.self, forKey: .jobStatistics)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.jobName, forKey: .jobName)
    try container.encodeIfPresent(self.jobConfiguration, forKey: .jobConfiguration)
    try container.encodeIfPresent(self.jobStatus, forKey: .jobStatus)
    try container.encodeIfPresent(self.jobStatistics, forKey: .jobStatistics)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.logging.v1.Job"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
