// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Job configuration information.
/// See the [Jobs](/bigquery/docs/reference/v2/jobs) API resource
/// for more details on individual fields.
public struct JobConfiguration: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// If true, don't actually run the job. Just check that it would run.
  public var dryRun: Swift.Bool = Swift.Bool()

  /// Labels provided for the job.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Job configuration information.
  public var configuration: OneOf_Configuration? = nil

  /// Initialize a new instance of `JobConfiguration`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = JobConfiguration().with { $0.query = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case query = "query"
    case load = "load"
    case extract = "extract"
    case tableCopy = "tableCopy"
    case dryRun = "dryRun"
    case labels = "labels"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.dryRun = try container.decode(Swift.Bool.self, forKey: .dryRun)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)

    var configuration: OneOf_Configuration? = nil
    let configurationCheckAndSet = {
      if configuration != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'configuration'"))
      }
      configuration = $0
    }
    if let query = try container.decodeIfPresent(JobConfiguration.Query?.self, forKey: .query) {
      try configurationCheckAndSet(.query(query))
    }
    if let load = try container.decodeIfPresent(JobConfiguration.Load?.self, forKey: .load) {
      try configurationCheckAndSet(.load(load))
    }
    if let extract = try container.decodeIfPresent(JobConfiguration.Extract?.self, forKey: .extract)
    {
      try configurationCheckAndSet(.extract(extract))
    }
    if let tableCopy = try container.decodeIfPresent(
      JobConfiguration.TableCopy?.self, forKey: .tableCopy)
    {
      try configurationCheckAndSet(.tableCopy(tableCopy))
    }
    self.configuration = configuration
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.dryRun, forKey: .dryRun)
    try container.encode(self.labels, forKey: .labels)

    if let choice = self.configuration {
      switch choice {
      case .query(let value):
        try container.encode(value, forKey: .query)
      case .load(let value):
        try container.encode(value, forKey: .load)
      case .extract(let value):
        try container.encode(value, forKey: .extract)
      case .tableCopy(let value):
        try container.encode(value, forKey: .tableCopy)
      }
    }
  }

  /// Describes a query job, which executes a SQL-like query.
  public struct Query: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The SQL query to run.
    public var query: Swift.String = Swift.String()

    /// The table where results are written.
    public var destinationTable: TableName? = nil

    /// Describes when a job is allowed to create a table:
    /// `CREATE_IF_NEEDED`, `CREATE_NEVER`.
    public var createDisposition: Swift.String = Swift.String()

    /// Describes how writes affect existing tables:
    /// `WRITE_TRUNCATE`, `WRITE_APPEND`, `WRITE_EMPTY`.
    public var writeDisposition: Swift.String = Swift.String()

    /// If a table name is specified without a dataset in a query,
    /// this dataset will be added to table name.
    public var defaultDataset: DatasetName? = nil

    /// Describes data sources outside BigQuery, if needed.
    public var tableDefinitions: [TableDefinition] = []

    /// Describes the priority given to the query:
    /// `QUERY_INTERACTIVE` or `QUERY_BATCH`.
    public var queryPriority: Swift.String = Swift.String()

    /// Result table encryption information. Set when non-default encryption is
    /// used.
    public var destinationTableEncryption: EncryptionInfo? = nil

    /// Type of the statement (e.g. SELECT, INSERT, CREATE_TABLE, CREATE_MODEL..)
    public var statementType: Swift.String = Swift.String()

    /// Initialize a new instance of `Query`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Query().with { $0.query = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.bigquery.logging.v1.JobConfiguration.Query"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Describes a load job, which loads data from an external source via
  /// the  import pipeline.
  public struct Load: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// URIs for the data to be imported. Only Google Cloud Storage URIs are
    /// supported.
    public var sourceUris: [Swift.String] = []

    /// The table schema in JSON format representation of a TableSchema.
    public var schemaJson: Swift.String = Swift.String()

    /// The table where the imported data is written.
    public var destinationTable: TableName? = nil

    /// Describes when a job is allowed to create a table:
    /// `CREATE_IF_NEEDED`, `CREATE_NEVER`.
    public var createDisposition: Swift.String = Swift.String()

    /// Describes how writes affect existing tables:
    /// `WRITE_TRUNCATE`, `WRITE_APPEND`, `WRITE_EMPTY`.
    public var writeDisposition: Swift.String = Swift.String()

    /// Result table encryption information. Set when non-default encryption is
    /// used.
    public var destinationTableEncryption: EncryptionInfo? = nil

    /// Initialize a new instance of `Load`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Load().with { $0.sourceUris = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.bigquery.logging.v1.JobConfiguration.Load"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Describes an extract job, which exports data to an external source
  /// via the  export pipeline.
  public struct Extract: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Google Cloud Storage URIs where extracted data should be written.
    public var destinationUris: [Swift.String] = []

    /// The source table.
    public var sourceTable: TableName? = nil

    /// Initialize a new instance of `Extract`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Extract().with { $0.destinationUris = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.bigquery.logging.v1.JobConfiguration.Extract"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Describes a copy job, which copies an existing table to another table.
  public struct TableCopy: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Source tables.
    public var sourceTables: [TableName] = []

    /// Destination table.
    public var destinationTable: TableName? = nil

    /// Describes when a job is allowed to create a table:
    /// `CREATE_IF_NEEDED`, `CREATE_NEVER`.
    public var createDisposition: Swift.String = Swift.String()

    /// Describes how writes affect existing tables:
    /// `WRITE_TRUNCATE`, `WRITE_APPEND`, `WRITE_EMPTY`.
    public var writeDisposition: Swift.String = Swift.String()

    /// Result table encryption information. Set when non-default encryption is
    /// used.
    public var destinationTableEncryption: EncryptionInfo? = nil

    /// Initialize a new instance of `TableCopy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TableCopy().with { $0.sourceTables = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.bigquery.logging.v1.JobConfiguration.TableCopy"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Job configuration information.
  public enum OneOf_Configuration: Codable, Equatable, Sendable {
    /// Query job information.
    indirect case query(JobConfiguration.Query?)
    /// Load job information.
    indirect case load(JobConfiguration.Load?)
    /// Extract job information.
    indirect case extract(JobConfiguration.Extract?)
    /// TableCopy job information.
    indirect case tableCopy(JobConfiguration.TableCopy?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.logging.v1.JobConfiguration"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
