// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Job configuration information.
/// See the [Jobs](/bigquery/docs/reference/v2/jobs) API resource
/// for more details on individual fields.
public struct JobConfiguration: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// If true, don't actually run the job. Just check that it would run.
  public var dryRun: Swift.Bool = Swift.Bool()

  /// Labels provided for the job.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Job configuration information.
  public var configuration: OneOf_Configuration? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `JobConfiguration`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = JobConfiguration().with { $0.query = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let query = CodingKeys(stringValue: "query")
    static let load = CodingKeys(stringValue: "load")
    static let extract = CodingKeys(stringValue: "extract")
    static let tableCopy = CodingKeys(stringValue: "tableCopy")
    static let dryRun = CodingKeys(stringValue: "dryRun")
    static let labels = CodingKeys(stringValue: "labels")

    static let _knownKeys: Set<Swift.String> = [
      "query",
      "load",
      "extract",
      "tableCopy",
      "dryRun",
      "labels",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .dryRun) {
      self.dryRun = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }

    var configuration: OneOf_Configuration? = nil
    let configurationCheckAndSet = {
      if configuration != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'configuration'"))
      }
      configuration = $0
    }
    if let query = try container.decodeIfPresent(JobConfiguration.Query?.self, forKey: .query) {
      try configurationCheckAndSet(.query(query))
    }
    if let load = try container.decodeIfPresent(JobConfiguration.Load?.self, forKey: .load) {
      try configurationCheckAndSet(.load(load))
    }
    if let extract = try container.decodeIfPresent(JobConfiguration.Extract?.self, forKey: .extract)
    {
      try configurationCheckAndSet(.extract(extract))
    }
    if let tableCopy = try container.decodeIfPresent(
      JobConfiguration.TableCopy?.self, forKey: .tableCopy)
    {
      try configurationCheckAndSet(.tableCopy(tableCopy))
    }
    self.configuration = configuration
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.dryRun, forKey: .dryRun)
    try container.encode(self.labels, forKey: .labels)

    if let choice = self.configuration {
      switch choice {
      case .query(let value):
        try container.encode(value, forKey: .query)
      case .load(let value):
        try container.encode(value, forKey: .load)
      case .extract(let value):
        try container.encode(value, forKey: .extract)
      case .tableCopy(let value):
        try container.encode(value, forKey: .tableCopy)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Describes a query job, which executes a SQL-like query.
  public struct Query: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The SQL query to run.
    public var query: Swift.String = Swift.String()

    /// The table where results are written.
    public var destinationTable: TableName? = nil

    /// Describes when a job is allowed to create a table:
    /// `CREATE_IF_NEEDED`, `CREATE_NEVER`.
    public var createDisposition: Swift.String = Swift.String()

    /// Describes how writes affect existing tables:
    /// `WRITE_TRUNCATE`, `WRITE_APPEND`, `WRITE_EMPTY`.
    public var writeDisposition: Swift.String = Swift.String()

    /// If a table name is specified without a dataset in a query,
    /// this dataset will be added to table name.
    public var defaultDataset: DatasetName? = nil

    /// Describes data sources outside BigQuery, if needed.
    public var tableDefinitions: [TableDefinition] = []

    /// Describes the priority given to the query:
    /// `QUERY_INTERACTIVE` or `QUERY_BATCH`.
    public var queryPriority: Swift.String = Swift.String()

    /// Result table encryption information. Set when non-default encryption is
    /// used.
    public var destinationTableEncryption: EncryptionInfo? = nil

    /// Type of the statement (e.g. SELECT, INSERT, CREATE_TABLE, CREATE_MODEL..)
    public var statementType: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Query`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Query().with { $0.query = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let query = CodingKeys(stringValue: "query")
      static let destinationTable = CodingKeys(stringValue: "destinationTable")
      static let createDisposition = CodingKeys(stringValue: "createDisposition")
      static let writeDisposition = CodingKeys(stringValue: "writeDisposition")
      static let defaultDataset = CodingKeys(stringValue: "defaultDataset")
      static let tableDefinitions = CodingKeys(stringValue: "tableDefinitions")
      static let queryPriority = CodingKeys(stringValue: "queryPriority")
      static let destinationTableEncryption = CodingKeys(stringValue: "destinationTableEncryption")
      static let statementType = CodingKeys(stringValue: "statementType")

      static let _knownKeys: Set<Swift.String> = [
        "query",
        "destinationTable",
        "createDisposition",
        "writeDisposition",
        "defaultDataset",
        "tableDefinitions",
        "queryPriority",
        "destinationTableEncryption",
        "statementType",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .query) {
        self.query = value
      }
      self.destinationTable = try container.decodeIfPresent(
        TableName.self, forKey: .destinationTable)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .createDisposition) {
        self.createDisposition = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .writeDisposition) {
        self.writeDisposition = value
      }
      self.defaultDataset = try container.decodeIfPresent(DatasetName.self, forKey: .defaultDataset)
      if let value = try container.decodeIfPresent(
        [TableDefinition].self, forKey: .tableDefinitions)
      {
        self.tableDefinitions = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .queryPriority) {
        self.queryPriority = value
      }
      self.destinationTableEncryption = try container.decodeIfPresent(
        EncryptionInfo.self, forKey: .destinationTableEncryption)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .statementType) {
        self.statementType = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.query, forKey: .query)
      try container.encodeIfPresent(self.destinationTable, forKey: .destinationTable)
      try container.encode(self.createDisposition, forKey: .createDisposition)
      try container.encode(self.writeDisposition, forKey: .writeDisposition)
      try container.encodeIfPresent(self.defaultDataset, forKey: .defaultDataset)
      try container.encode(self.tableDefinitions, forKey: .tableDefinitions)
      try container.encode(self.queryPriority, forKey: .queryPriority)
      try container.encodeIfPresent(
        self.destinationTableEncryption, forKey: .destinationTableEncryption)
      try container.encode(self.statementType, forKey: .statementType)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.bigquery.logging.v1.JobConfiguration.Query"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Describes a load job, which loads data from an external source via
  /// the  import pipeline.
  public struct Load: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// URIs for the data to be imported. Only Google Cloud Storage URIs are
    /// supported.
    public var sourceUris: [Swift.String] = []

    /// The table schema in JSON format representation of a TableSchema.
    public var schemaJson: Swift.String = Swift.String()

    /// The table where the imported data is written.
    public var destinationTable: TableName? = nil

    /// Describes when a job is allowed to create a table:
    /// `CREATE_IF_NEEDED`, `CREATE_NEVER`.
    public var createDisposition: Swift.String = Swift.String()

    /// Describes how writes affect existing tables:
    /// `WRITE_TRUNCATE`, `WRITE_APPEND`, `WRITE_EMPTY`.
    public var writeDisposition: Swift.String = Swift.String()

    /// Result table encryption information. Set when non-default encryption is
    /// used.
    public var destinationTableEncryption: EncryptionInfo? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Load`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Load().with { $0.sourceUris = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let sourceUris = CodingKeys(stringValue: "sourceUris")
      static let schemaJson = CodingKeys(stringValue: "schemaJson")
      static let destinationTable = CodingKeys(stringValue: "destinationTable")
      static let createDisposition = CodingKeys(stringValue: "createDisposition")
      static let writeDisposition = CodingKeys(stringValue: "writeDisposition")
      static let destinationTableEncryption = CodingKeys(stringValue: "destinationTableEncryption")

      static let _knownKeys: Set<Swift.String> = [
        "sourceUris",
        "schemaJson",
        "destinationTable",
        "createDisposition",
        "writeDisposition",
        "destinationTableEncryption",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .sourceUris) {
        self.sourceUris = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .schemaJson) {
        self.schemaJson = value
      }
      self.destinationTable = try container.decodeIfPresent(
        TableName.self, forKey: .destinationTable)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .createDisposition) {
        self.createDisposition = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .writeDisposition) {
        self.writeDisposition = value
      }
      self.destinationTableEncryption = try container.decodeIfPresent(
        EncryptionInfo.self, forKey: .destinationTableEncryption)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.sourceUris, forKey: .sourceUris)
      try container.encode(self.schemaJson, forKey: .schemaJson)
      try container.encodeIfPresent(self.destinationTable, forKey: .destinationTable)
      try container.encode(self.createDisposition, forKey: .createDisposition)
      try container.encode(self.writeDisposition, forKey: .writeDisposition)
      try container.encodeIfPresent(
        self.destinationTableEncryption, forKey: .destinationTableEncryption)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.bigquery.logging.v1.JobConfiguration.Load"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Describes an extract job, which exports data to an external source
  /// via the  export pipeline.
  public struct Extract: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Google Cloud Storage URIs where extracted data should be written.
    public var destinationUris: [Swift.String] = []

    /// The source table.
    public var sourceTable: TableName? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Extract`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Extract().with { $0.destinationUris = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let destinationUris = CodingKeys(stringValue: "destinationUris")
      static let sourceTable = CodingKeys(stringValue: "sourceTable")

      static let _knownKeys: Set<Swift.String> = [
        "destinationUris",
        "sourceTable",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .destinationUris) {
        self.destinationUris = value
      }
      self.sourceTable = try container.decodeIfPresent(TableName.self, forKey: .sourceTable)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.destinationUris, forKey: .destinationUris)
      try container.encodeIfPresent(self.sourceTable, forKey: .sourceTable)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.bigquery.logging.v1.JobConfiguration.Extract"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Describes a copy job, which copies an existing table to another table.
  public struct TableCopy: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Source tables.
    public var sourceTables: [TableName] = []

    /// Destination table.
    public var destinationTable: TableName? = nil

    /// Describes when a job is allowed to create a table:
    /// `CREATE_IF_NEEDED`, `CREATE_NEVER`.
    public var createDisposition: Swift.String = Swift.String()

    /// Describes how writes affect existing tables:
    /// `WRITE_TRUNCATE`, `WRITE_APPEND`, `WRITE_EMPTY`.
    public var writeDisposition: Swift.String = Swift.String()

    /// Result table encryption information. Set when non-default encryption is
    /// used.
    public var destinationTableEncryption: EncryptionInfo? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `TableCopy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TableCopy().with { $0.sourceTables = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let sourceTables = CodingKeys(stringValue: "sourceTables")
      static let destinationTable = CodingKeys(stringValue: "destinationTable")
      static let createDisposition = CodingKeys(stringValue: "createDisposition")
      static let writeDisposition = CodingKeys(stringValue: "writeDisposition")
      static let destinationTableEncryption = CodingKeys(stringValue: "destinationTableEncryption")

      static let _knownKeys: Set<Swift.String> = [
        "sourceTables",
        "destinationTable",
        "createDisposition",
        "writeDisposition",
        "destinationTableEncryption",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([TableName].self, forKey: .sourceTables) {
        self.sourceTables = value
      }
      self.destinationTable = try container.decodeIfPresent(
        TableName.self, forKey: .destinationTable)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .createDisposition) {
        self.createDisposition = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .writeDisposition) {
        self.writeDisposition = value
      }
      self.destinationTableEncryption = try container.decodeIfPresent(
        EncryptionInfo.self, forKey: .destinationTableEncryption)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.sourceTables, forKey: .sourceTables)
      try container.encodeIfPresent(self.destinationTable, forKey: .destinationTable)
      try container.encode(self.createDisposition, forKey: .createDisposition)
      try container.encode(self.writeDisposition, forKey: .writeDisposition)
      try container.encodeIfPresent(
        self.destinationTableEncryption, forKey: .destinationTableEncryption)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.bigquery.logging.v1.JobConfiguration.TableCopy"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Job configuration information.
  public enum OneOf_Configuration: Codable, Equatable, Sendable {
    /// Query job information.
    indirect case query(JobConfiguration.Query?)
    /// Load job information.
    indirect case load(JobConfiguration.Load?)
    /// Extract job information.
    indirect case extract(JobConfiguration.Extract?)
    /// TableCopy job information.
    indirect case tableCopy(JobConfiguration.TableCopy?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.logging.v1.JobConfiguration"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
