// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Job query request.
public struct JobQueryRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The query.
  public var query: Swift.String = Swift.String()

  /// The maximum number of results.
  public var maxResults: Swift.UInt32 = Swift.UInt32()

  /// The default dataset for tables that do not have a dataset specified.
  public var defaultDataset: DatasetName? = nil

  /// Project that the query should be charged to.
  public var projectId: Swift.String = Swift.String()

  /// If true, don't actually run the job. Just check that it would run.
  public var dryRun: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `JobQueryRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = JobQueryRequest().with { $0.query = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.logging.v1.JobQueryRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
