// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Job query request.
public struct JobQueryRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The query.
  public var query: Swift.String = Swift.String()

  /// The maximum number of results.
  public var maxResults: Swift.UInt32 = Swift.UInt32()

  /// The default dataset for tables that do not have a dataset specified.
  public var defaultDataset: DatasetName? = nil

  /// Project that the query should be charged to.
  public var projectId: Swift.String = Swift.String()

  /// If true, don't actually run the job. Just check that it would run.
  public var dryRun: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `JobQueryRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = JobQueryRequest().with { $0.query = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let query = CodingKeys(stringValue: "query")
    static let maxResults = CodingKeys(stringValue: "maxResults")
    static let defaultDataset = CodingKeys(stringValue: "defaultDataset")
    static let projectId = CodingKeys(stringValue: "projectId")
    static let dryRun = CodingKeys(stringValue: "dryRun")

    static let _knownKeys: Set<Swift.String> = [
      "query",
      "maxResults",
      "defaultDataset",
      "projectId",
      "dryRun",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .query) {
      self.query = value
    }
    if let value = try container.decodeIfPresent(Swift.UInt32.self, forKey: .maxResults) {
      self.maxResults = value
    }
    self.defaultDataset = try container.decodeIfPresent(DatasetName.self, forKey: .defaultDataset)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .projectId) {
      self.projectId = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .dryRun) {
      self.dryRun = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.query, forKey: .query)
    try container.encode(self.maxResults, forKey: .maxResults)
    try container.encodeIfPresent(self.defaultDataset, forKey: .defaultDataset)
    try container.encode(self.projectId, forKey: .projectId)
    try container.encode(self.dryRun, forKey: .dryRun)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.logging.v1.JobQueryRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
