// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Job statistics that may change after a job starts.
public struct JobStatistics: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Time when the job was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Time when the job started.
  public var startTime: GoogleWKT.WKTTimestamp? = nil

  /// Time when the job ended.
  public var endTime: GoogleWKT.WKTTimestamp? = nil

  /// Total bytes processed for a job.
  public var totalProcessedBytes: Swift.Int64 = Swift.Int64()

  /// Processed bytes, adjusted by the job's CPU usage.
  public var totalBilledBytes: Swift.Int64 = Swift.Int64()

  /// The tier assigned by CPU-based billing.
  public var billingTier: Swift.Int32 = Swift.Int32()

  /// The total number of slot-ms consumed by the query job.
  public var totalSlotMs: Swift.Int64 = Swift.Int64()

  /// Reservation usage. This field reported misleading information and will
  /// no longer be populated. Aggregate usage of all jobs submitted to a
  /// reservation should provide a more reliable indicator of reservation
  /// imbalance.
  @available(*, deprecated)
  public var reservationUsage: [JobStatistics.ReservationResourceUsage] = []

  /// Reservation name or "unreserved" for on-demand resource usage.
  public var reservation: Swift.String = Swift.String()

  /// The first N tables accessed by the query job. Older queries that
  /// reference a large number of tables may not have all of their
  /// tables in this list. You can use the total_tables_processed count to
  /// know how many total tables were read in the query. For new queries,
  /// there is currently no limit.
  public var referencedTables: [TableName] = []

  /// Total number of unique tables referenced in the query.
  public var totalTablesProcessed: Swift.Int32 = Swift.Int32()

  /// The first N views accessed by the query job. Older queries that
  /// reference a large number of views may not have all of their
  /// views in this list. You can use the total_tables_processed count to
  /// know how many total tables were read in the query. For new queries,
  /// there is currently no limit.
  public var referencedViews: [TableName] = []

  /// Total number of unique views referenced in the query.
  public var totalViewsProcessed: Swift.Int32 = Swift.Int32()

  /// Number of output rows produced by the query job.
  public var queryOutputRowCount: Swift.Int64 = Swift.Int64()

  /// Total bytes loaded for an import job.
  public var totalLoadOutputBytes: Swift.Int64 = Swift.Int64()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `JobStatistics`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = JobStatistics().with { $0.createTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let createTime = CodingKeys(stringValue: "createTime")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let endTime = CodingKeys(stringValue: "endTime")
    static let totalProcessedBytes = CodingKeys(stringValue: "totalProcessedBytes")
    static let totalBilledBytes = CodingKeys(stringValue: "totalBilledBytes")
    static let billingTier = CodingKeys(stringValue: "billingTier")
    static let totalSlotMs = CodingKeys(stringValue: "totalSlotMs")
    static let reservationUsage = CodingKeys(stringValue: "reservationUsage")
    static let reservation = CodingKeys(stringValue: "reservation")
    static let referencedTables = CodingKeys(stringValue: "referencedTables")
    static let totalTablesProcessed = CodingKeys(stringValue: "totalTablesProcessed")
    static let referencedViews = CodingKeys(stringValue: "referencedViews")
    static let totalViewsProcessed = CodingKeys(stringValue: "totalViewsProcessed")
    static let queryOutputRowCount = CodingKeys(stringValue: "queryOutputRowCount")
    static let totalLoadOutputBytes = CodingKeys(stringValue: "totalLoadOutputBytes")

    static let _knownKeys: Set<Swift.String> = [
      "createTime",
      "startTime",
      "endTime",
      "totalProcessedBytes",
      "totalBilledBytes",
      "billingTier",
      "totalSlotMs",
      "reservationUsage",
      "reservation",
      "referencedTables",
      "totalTablesProcessed",
      "referencedViews",
      "totalViewsProcessed",
      "queryOutputRowCount",
      "totalLoadOutputBytes",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.startTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .startTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .endTime)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .totalProcessedBytes) {
      self.totalProcessedBytes = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .totalBilledBytes) {
      self.totalBilledBytes = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .billingTier) {
      self.billingTier = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .totalSlotMs) {
      self.totalSlotMs = value
    }
    if let value = try container.decodeIfPresent(
      [JobStatistics.ReservationResourceUsage].self, forKey: .reservationUsage)
    {
      self.reservationUsage = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .reservation) {
      self.reservation = value
    }
    if let value = try container.decodeIfPresent([TableName].self, forKey: .referencedTables) {
      self.referencedTables = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .totalTablesProcessed) {
      self.totalTablesProcessed = value
    }
    if let value = try container.decodeIfPresent([TableName].self, forKey: .referencedViews) {
      self.referencedViews = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .totalViewsProcessed) {
      self.totalViewsProcessed = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .queryOutputRowCount) {
      self.queryOutputRowCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .totalLoadOutputBytes) {
      self.totalLoadOutputBytes = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    try container.encode(self.totalProcessedBytes, forKey: .totalProcessedBytes)
    try container.encode(self.totalBilledBytes, forKey: .totalBilledBytes)
    try container.encode(self.billingTier, forKey: .billingTier)
    try container.encode(self.totalSlotMs, forKey: .totalSlotMs)
    try container.encode(self.reservationUsage, forKey: .reservationUsage)
    try container.encode(self.reservation, forKey: .reservation)
    try container.encode(self.referencedTables, forKey: .referencedTables)
    try container.encode(self.totalTablesProcessed, forKey: .totalTablesProcessed)
    try container.encode(self.referencedViews, forKey: .referencedViews)
    try container.encode(self.totalViewsProcessed, forKey: .totalViewsProcessed)
    try container.encode(self.queryOutputRowCount, forKey: .queryOutputRowCount)
    try container.encode(self.totalLoadOutputBytes, forKey: .totalLoadOutputBytes)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Job resource usage breakdown by reservation.
  public struct ReservationResourceUsage: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Reservation name or "unreserved" for on-demand resources usage.
    public var name: Swift.String = Swift.String()

    /// Total slot milliseconds used by the reservation for a particular job.
    public var slotMs: Swift.Int64 = Swift.Int64()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ReservationResourceUsage`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ReservationResourceUsage().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let name = CodingKeys(stringValue: "name")
      static let slotMs = CodingKeys(stringValue: "slotMs")

      static let _knownKeys: Set<Swift.String> = [
        "name",
        "slotMs",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .slotMs) {
        self.slotMs = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.slotMs, forKey: .slotMs)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.bigquery.logging.v1.JobStatistics.ReservationResourceUsage"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.logging.v1.JobStatistics"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
