// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Job statistics that may change after a job starts.
public struct JobStatistics: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Time when the job was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Time when the job started.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// Time when the job ended.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// Total bytes processed for a job.
  public var totalProcessedBytes: Swift.Int64 = Swift.Int64()

  /// Processed bytes, adjusted by the job's CPU usage.
  public var totalBilledBytes: Swift.Int64 = Swift.Int64()

  /// The tier assigned by CPU-based billing.
  public var billingTier: Swift.Int32 = Swift.Int32()

  /// The total number of slot-ms consumed by the query job.
  public var totalSlotMs: Swift.Int64 = Swift.Int64()

  /// Reservation usage. This field reported misleading information and will
  /// no longer be populated. Aggregate usage of all jobs submitted to a
  /// reservation should provide a more reliable indicator of reservation
  /// imbalance.
  @available(*, deprecated)
  public var reservationUsage: [JobStatistics.ReservationResourceUsage] = []

  /// Reservation name or "unreserved" for on-demand resource usage.
  public var reservation: Swift.String = Swift.String()

  /// The first N tables accessed by the query job. Older queries that
  /// reference a large number of tables may not have all of their
  /// tables in this list. You can use the total_tables_processed count to
  /// know how many total tables were read in the query. For new queries,
  /// there is currently no limit.
  public var referencedTables: [TableName] = []

  /// Total number of unique tables referenced in the query.
  public var totalTablesProcessed: Swift.Int32 = Swift.Int32()

  /// The first N views accessed by the query job. Older queries that
  /// reference a large number of views may not have all of their
  /// views in this list. You can use the total_tables_processed count to
  /// know how many total tables were read in the query. For new queries,
  /// there is currently no limit.
  public var referencedViews: [TableName] = []

  /// Total number of unique views referenced in the query.
  public var totalViewsProcessed: Swift.Int32 = Swift.Int32()

  /// Number of output rows produced by the query job.
  public var queryOutputRowCount: Swift.Int64 = Swift.Int64()

  /// Total bytes loaded for an import job.
  public var totalLoadOutputBytes: Swift.Int64 = Swift.Int64()

  /// Initialize a new instance of `JobStatistics`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = JobStatistics().with { $0.createTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Job resource usage breakdown by reservation.
  public struct ReservationResourceUsage: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Reservation name or "unreserved" for on-demand resources usage.
    public var name: Swift.String = Swift.String()

    /// Total slot milliseconds used by the reservation for a particular job.
    public var slotMs: Swift.Int64 = Swift.Int64()

    /// Initialize a new instance of `ReservationResourceUsage`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ReservationResourceUsage().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.bigquery.logging.v1.JobStatistics.ReservationResourceUsage"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.logging.v1.JobStatistics"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
