// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Describes a BigQuery table.
/// See the [Table](/bigquery/docs/reference/v2/tables) API resource
/// for more details on individual fields.
/// Note: `Table.schema` has been deprecated in favor of `Table.schemaJson`.
/// `Table.schema` may continue to be present in your logs during this
/// transition.
public struct Table: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The name of the table.
  public var tableName: TableName? = nil

  /// User-provided metadata for the table.
  public var info: TableInfo? = nil

  /// A JSON representation of the table's schema.
  public var schemaJson: Swift.String = Swift.String()

  /// If present, this is a virtual table defined by a SQL query.
  public var view: TableViewDefinition? = nil

  /// The expiration date for the table, after which the table
  /// is deleted and the storage reclaimed.
  /// If not present, the table persists indefinitely.
  public var expireTime: GoogleCloudWKT.Timestamp? = nil

  /// The time the table was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// The time the table was last truncated
  /// by an operation with a `writeDisposition` of `WRITE_TRUNCATE`.
  public var truncateTime: GoogleCloudWKT.Timestamp? = nil

  /// The time the table was last modified.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// The table encryption information. Set when non-default encryption is used.
  public var encryption: EncryptionInfo? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `Table`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Table().with { $0.tableName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let tableName = CodingKeys(stringValue: "tableName")
    static let info = CodingKeys(stringValue: "info")
    static let schemaJson = CodingKeys(stringValue: "schemaJson")
    static let view = CodingKeys(stringValue: "view")
    static let expireTime = CodingKeys(stringValue: "expireTime")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let truncateTime = CodingKeys(stringValue: "truncateTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let encryption = CodingKeys(stringValue: "encryption")

    static let _knownKeys: Set<Swift.String> = [
      "tableName",
      "info",
      "schemaJson",
      "view",
      "expireTime",
      "createTime",
      "truncateTime",
      "updateTime",
      "encryption",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.tableName = try container.decodeIfPresent(TableName.self, forKey: .tableName)
    self.info = try container.decodeIfPresent(TableInfo.self, forKey: .info)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .schemaJson) {
      self.schemaJson = value
    }
    self.view = try container.decodeIfPresent(TableViewDefinition.self, forKey: .view)
    self.expireTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .expireTime)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.truncateTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .truncateTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .updateTime)
    self.encryption = try container.decodeIfPresent(EncryptionInfo.self, forKey: .encryption)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.tableName, forKey: .tableName)
    try container.encodeIfPresent(self.info, forKey: .info)
    try container.encode(self.schemaJson, forKey: .schemaJson)
    try container.encodeIfPresent(self.view, forKey: .view)
    try container.encodeIfPresent(self.expireTime, forKey: .expireTime)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.truncateTime, forKey: .truncateTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.encryption, forKey: .encryption)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.logging.v1.Table"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
